trigger:
- feature/*
- master

stages:
- stage: Terraform_Setup
  displayName: Terraform Setup Plan
  jobs:
  
  - job: Terraform_Install
    pool: RohtasPool
    steps:
    - checkout: self
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/DEV'
        backendServiceArm: 'AzureInfraProject'
        backendAzureRmOverrideSubscriptionID: 'e939c0ee-ab91-49f3-b854-6a4cab5b9219'
        backendAzureRmResourceGroupName: 'robinson'
        backendAzureRmStorageAccountName: 'robinteststorage1'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'prod.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/DEV'
        environmentServiceNameAzureRM: 'AzureInfraProject'

- stage: Terraform_Apply
  displayName: Terraform Setup Apply
  jobs:

  - job: Terraform_Init
    pool: RohtasPool
    steps:
    - checkout: self
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/DEV'
        backendServiceArm: 'AzureInfraProject'
        backendAzureRmOverrideSubscriptionID: 'e939c0ee-ab91-49f3-b854-6a4cab5b9219'
        backendAzureRmResourceGroupName: 'robinson'
        backendAzureRmStorageAccountName: 'robinteststorage1'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'prod.tfstate'
    - task: TerraformTask@5
      displayName: apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'AzureInfraProject'